### ISSUE TITLE
[Deployment] App not deploying on Heroku

### ISSUE THREAD

**Issue by Saakshaat** [dsc-umass/project-matching#10]
**Describe the bug**
The application isn't deploying on Heroku. I've set up the Heroku remote, pushed to its git but during deployment, the push fails.

**To Reproduce**
1. Set the remote to Heroku: `heroku git:remote -a project-matcha`
2. Add and Commit all files to this remote: `git commit -am "First Deployment"`
3. Push the branch to Heroku: `git push heroku master` 
If there's a sepereate branch for deployment: `git push heroku <branch-name>`
If the local branch name is different from the heroku branch that you're trying to push to:
`git push heroku <local-branch-name>:<remote-branch-name>`
4. See the error

**Expected behavior**
The code should be built and deployed to Heroku but the build fails.

**Error Log**
```
remote:        Compiling...
remote:        Compilation failed:
remote:        ModuleNotFoundError: Module not found: Error: Can't resolve 'turbolinks' in '/tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript/packs'
remote:            at factory.create (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/lib/Compilation.js:925:10)
remote:            at factory (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
remote:            at resolver (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
remote:            at asyncLib.parallel (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
remote:            at /tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/neo-async/async.js:2830:7
remote:            at /tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/neo-async/async.js:6877:13
remote:            at normalResolver.resolve (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
remote:            at doResolve (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
remote:            at hook.callAsync (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn0 (eval at create (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
remote:            at resolver.doResolve (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
remote:            at hook.callAsync (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn0 (eval at create (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
remote:            at hook.callAsync (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn0 (eval at create (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
remote:            at resolver.doResolve (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
remote:            at hook.callAsync (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn41 (eval at create (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
remote:            at resolver.doResolve (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40)
remote:            at hook.callAsync (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn0 (eval at create (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
remote:            at hook.callAsync (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn1 (eval at create (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
remote:            at args (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/node_modules/enhanced-resolve/lib/forEachBail.js:30:14)
remote:            at hook.callAsync (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn0 (eval at create (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
remote:            at resolver.doResolve (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
remote:            at hook.callAsync (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn0 (eval at create (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
remote:            at hook.callAsync (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn0 (eval at create (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
remote:            at resolver.doResolve (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
remote:            at hook.callAsync (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn42 (eval at create (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
remote:            at hook.callAsync (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn0 (eval at create (/tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
remote:        resolve 'turbolinks' in '/tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript/packs'
remote:          Parsed request is a module
remote:          using description file: /tmp/build_1a4a7a26461e0910c2cc369051c39226/package.json (relative path: ./app/javascript/packs)
remote:            Field 'browser' doesn't contain a valid alias configuration
remote:            resolve as module
remote:              looking for modules in /tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript
remote:                using description file: /tmp/build_1a4a7a26461e0910c2cc369051c39226/package.json (relative path: ./app/javascript)
remote:                  Field 'browser' doesn't contain a valid alias configuration
remote:                  using description file: /tmp/build_1a4a7a26461e0910c2cc369051c39226/package.json (relative path: ./app/javascript/turbolinks)
remote:                    no extension
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript/turbolinks doesn't exist
remote:                    .mjs
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript/turbolinks.mjs doesn't exist
remote:                    .js
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript/turbolinks.js doesn't exist
remote:                    .sass
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript/turbolinks.sass doesn't exist
remote:                    .scss
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript/turbolinks.scss doesn't exist
remote:                    .css
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript/turbolinks.css doesn't exist
remote:                    .module.sass
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript/turbolinks.module.sass doesn't exist
remote:                    .module.scss
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript/turbolinks.module.scss doesn't exist
remote:                    .module.css
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript/turbolinks.module.css doesn't exist
remote:                    .png
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript/turbolinks.png doesn't exist
remote:                    .svg
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript/turbolinks.svg doesn't exist
remote:                    .gif
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript/turbolinks.gif doesn't exist
remote:                    .jpeg
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript/turbolinks.jpeg doesn't exist
remote:                    .jpg
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript/turbolinks.jpg doesn't exist
remote:                    as directory
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript/turbolinks doesn't exist
remote:              /tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript/packs/node_modules doesn't exist or is not a directory
remote:              /tmp/build_1a4a7a26461e0910c2cc369051c39226/app/javascript/node_modules doesn't exist or is not a directory
remote:              /tmp/build_1a4a7a26461e0910c2cc369051c39226/app/node_modules doesn't exist or is not a directory
remote:              /tmp/node_modules doesn't exist or is not a directory
remote:              /node_modules doesn't exist or is not a directory
remote:              looking for modules in /tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules
remote:                using description file: /tmp/build_1a4a7a26461e0910c2cc369051c39226/package.json (relative path: ./node_modules)
remote:                  Field 'browser' doesn't contain a valid alias configuration
remote:                  using description file: /tmp/build_1a4a7a26461e0910c2cc369051c39226/package.json (relative path: ./node_modules/turbolinks)
remote:                    no extension
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/turbolinks doesn't exist
remote:                    .mjs
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/turbolinks.mjs doesn't exist
remote:                    .js
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/turbolinks.js doesn't exist
remote:                    .sass
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/turbolinks.sass doesn't exist
remote:                    .scss
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/turbolinks.scss doesn't exist
remote:                    .css
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/turbolinks.css doesn't exist
remote:                    .module.sass
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/turbolinks.module.sass doesn't exist
remote:                    .module.scss
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/turbolinks.module.scss doesn't exist
remote:                    .module.css
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/turbolinks.module.css doesn't exist
remote:                    .png
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/turbolinks.png doesn't exist
remote:                    .svg
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/turbolinks.svg doesn't exist
remote:                    .gif
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/turbolinks.gif doesn't exist
remote:                    .jpeg
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/turbolinks.jpeg doesn't exist
remote:                    .jpg
remote:                      Field 'browser' doesn't contain a valid alias configuration
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/turbolinks.jpg doesn't exist
remote:                    as directory
remote:                      /tmp/build_1a4a7a26461e0910c2cc369051c39226/node_modules/turbolinks doesn't exist
remote:        
remote: 
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to peaceful-meadow-81237.
remote: 
To https://git.heroku.com/peaceful-meadow-81237.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/peaceful-meadow-81237.git'

```

**Possible Issue**
The Gemfile does not have a group for production. As per the Heroku tutorial, I defined it as 
```
group :production do
gem 'pg', '1.1.4'
end
```
But the gem for PostgreSQL was already defined so I removed its initial definition and defined it within the group definition as
```
group :production do
   gem 'pg', '>= 0.18', '< 2.0'
end
```
Then I ran `bundle install production`. But this didn't affect the build status with Heroku.

**Comment by abhinavtripathy** [comment]
@CodyRichter

**Comment by ykamin-booth** [comment]
Did you figure this issue out? Looks like I'm having the same issue on a different project.

**Comment by harsh183** [comment]
We ended up doing a rails6 refresh of the project and it worked out fine. What's the issue with your project? I can get to help.

**Comment by harsh183** [comment]
@ykamin-booth try https://devcenter.heroku.com/articles/sqlite3

**Comment by ykamin-booth** [comment]
Thanks! I also ended up just doing a rails6 refresh and got everything to work.

**Comment by harsh183** [comment]
Awesome! Good luck with your project.
